# serverless.yml

service: apollo-lambda
provider:
  name: aws
  profile: serverless
  runtime: nodejs16.x
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphqlLambda.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true
plugins:
  - serverless-offline